from . import gitlab
from . import group
from . import project
from . import commit
from . import issue
from . import merge_request
from . import note
from . import merge_request_approval
from . import res_partner
