{
    "name": "Gitlab",
    "category": "Tools",
    "version": "18.0.1.0.0",
    "author": "Onestein, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/server-backend",
    "license": "AGPL-3",
    "depends": ["base", "queue_job"],
    "external_dependencies": {"python": ["python-gitlab"]},
    "demo": ["demo/gitlab_data.xml"],
    "data": [
        "security/ir_model_access.xml",
        "data/ir_cron_data.xml",
        "data/queue_job_function_data.xml",
        "views/gitlab_view.xml",
        "views/group_view.xml",
        "views/project_view.xml",
        "views/commit_view.xml",
        "views/issue_view.xml",
        "views/merge_request_view.xml",
        "views/note_view.xml",
        "views/merge_request_approval_view.xml",
        "views/res_partner_view.xml",
        "menuitems.xml",
    ],
}
